SistemaLogin/Areas/Seguranca/Controllers/PapelAdminController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using SistemaLogin.Areas.Seguranca.Data;
using SistemaLogin.Infraestrutura;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace SistemaLogin.Areas.Seguranca.Controllers
{
    public class PapelAdminController : Controller
    {

        // GET: Seguranca/PapelAdmin
        public ActionResult Index()
        {
            return View(RoleManager.Roles);
        }
        private GerenciadorPapel RoleManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<GerenciadorPapel>();
            }
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create([Required] string nome)
        {
            if (ModelState.IsValid)
            {
                IdentityResult result = RoleManager.Create(new Papel(nome));

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    AddErrorsFromResult(result);
                }

            }
            return View(nome);
        }
        private void AddErrorsFromResult(IdentityResult result)
        {
            foreach (string error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }

        public ActionResult Edit(string id)
        {
            Papel papel = RoleManager.FindById(id);
            string[] memberIDs = papel.Users.Select(x => x.UserId).ToArray();
            IEnumerable<Usuario> membros = UserManager.Users.Where(x => memberIDs.Any(y => y == x.Id));
            IEnumerable<Usuario> naoMemrbos = UserManager.Users.Except(membros);

            return View(new PapelEditModel
            {
                Role = papel,
                Membros = membros,
                NaoMenbros = naoMemrbos
            });
        }

        [HttpPost]
        public ActionResult Edit(PapelModificationModel model)
        {
            IdentityResult result;

            if (ModelState.IsValid)
            {
                foreach (string userId in model.IdsParaAdicionar ?? new string[] { })
                {
                    result = UserManager.AddToRole(userId, model.NomePapel);

                    if (!result.Succeeded)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                }
                foreach (string userId in model.IdsParaRemover ?? new string[] { })
                {
                    result = UserManager.RemoveFromRole(userId, model.NomePapel);

                    if (!result.Succeeded)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                }
                return RedirectToAction("Index");
            }
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }
        private GerenciadorUsuario UserManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<GerenciadorUsuario>();
            }
        }

    }
}

SistemaLogin/Areas/Seguranca/Views/PapelAdmin/Create.cshtml
@model SistemaLogin.Areas.Seguranca.Data.Papel

@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <br />
    <div class="panel panel-primary">
        <div class="panel-heading">
            Registro de um NOVO PAPEL
        </div>
        <br />
        <div class="panel-body">
            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-md-12">
                        <label>Nome</label>
                        <input name="nome" value="@Model" class="form-control" />
                    </div>
                </div>
            </div>
        </div>
        <br />
        <div class="container">
            <div class="row">
                <div class="col d-grid gap-2">
                    @Html.ActionLink("Retornar para a listagem de PAPÉIS", "Index", null, new { @class = "btn btn-default" })
                </div>
                <div class="col d-grid gap-2">
                    <input type="submit" value="Adicionar Papel" class="btn btn-danger" />
                </div>
            </div>
        </div>
        <br/>
    </div>
}

SistemaLogin/Areas/Seguranca/Views/PapelAdmin/Edit.cshtml
@using SistemaLogin.Areas.Seguranca.Data
@model PapelEditModel

@{ Layout = "~/Views/Shared/_LayoutAdmin.cshtml"; }

<div>
    @Html.ValidationSummary()
    @using (Html.BeginForm())
    {
<input type="hidden" name="nomePapel" value="@Model.Role.Name" />
                <div class="panel panel-primary">
                    <div class="panel-heading">Adicionar para @Model.Role.Name</div>
                    <table class="table table-striped">
                        @if (Model.NaoMenbros.Count() == 0)
                        {
        <tr><td colspan="2">Todos os usuários são membros.</td></tr> }
                        else
                        {
        <tr><td>Usuários</td><td>Adicionar ao Papel</td></tr> foreach (Usuario usuario in Model.NaoMenbros)
                            {
        <tr>
            <td>@usuario.UserName</td>
            <td>
                <input type="checkbox" name="IdsParaAdicionar" value="@usuario.Id" />
            </td>
        </tr>}
                        }
                    </table>
                </div>

                                <div class="panel panel-primary">
                                    <div class="panel-heading">Remover de @Model.Role.Name</div>
                                    <table class="table table-striped">
                                        @if (Model.Membros.Count() == 0)
                                        {
                        <tr><td colspan="2">Sem usuários membros.</td></tr> }
                                        else
                                        {
                        <tr><td>Usuários</td><td>Remover do Papel</td></tr> foreach (Usuario usuario in Model.Membros)
                                            {
                        <tr>
                            <td>@usuario.UserName</td>
                            <td>
                                <input type="checkbox" name="IdsParaRemover" value="@usuario.Id" />
                            </td>
                        </tr>}
                                        }
                                    </table>
                                </div>
                                                <button type="submit" class="btn btn-primary">Gravar alterações</button>
                                                                @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-default" })}
<br />
</div>

SistemaLogin/Areas/Seguranca/Views/PapelAdmin/Index.cshtml
@using SistemaLogin.Infraestrutura
@using SistemaLogin.Areas.Seguranca.Data
@model IEnumerable<SistemaLogin.Areas.Seguranca.Data.Papel>

@{ 
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="panel panel-primary">
    <br/>
    <div class="panel-heading panel-footer panel-info">
        Registro de Papéis dos Usuários
    </div>
    <br/>
    <table class="table table-striped table-hover">
        <tr>
            <th>ID</th>
            <th>Usuário</th>
            <th>Papéis</th>
            <th></th>
        </tr>
        @if (Model.Count() == 0)
        {
            <tr>
                <td colspan="4" class="text-center"> Sem papéis registrados</td>
            </tr> 
        }
        else
        {
            foreach (Papel role in Model)
            { 
                <tr>
                <td>@role.Id</td>
                <td>@role.Name</td>
                <td>@if (role.Users == null || role.Users.Count == 0)
                    {
                        @: Sem usuários no papel.
                    }
                    else
                    {
                        <p>
                        @string.Join(", ", role.Users.Select(x => Html.GetUserName(x.UserId)))
                        </p>
                    }
                </td>
                <td>@using (Html.BeginForm("Delete", "PapelAdmin", new { id = role.Id }))
                    {
                        @Html.ActionLink("Alterar", "Edit", new { id = role.Id }, new { @class = "btn btn-primary btn-xs" })
                        <button class="btn btn-primary btn-xs" type="submit">Delete</button>
                    }
                </td>
                </tr>
            }
        }
    </table> 
    @Html.ActionLink("Criar um novo papel", "Create", null, new { @class = "btn btn-primary" })
    <br/>
    <br/>
</div>